feat: add react typescript template
vitejs/create-vite-app pull request #7
Opened 2020-05-22 08:32 UTC by xiaoxiangmoe

2020-05-23 14:05 UTC, xiaoxiangmoe commented
@yyx990803 Can you review it? Thank you.

2020-05-25 18:22 UTC, xiaoxiangmoe commented
@yyx990803 Is there anything else I need to add?

2020-05-25 18:29 UTC, yyx990803 requested changes

2020-05-25 18:29 UTC, yyx990803 commented on template-react-typescript/src/react-app-env.d.ts
> +declare module '*.bmp' {
Vite doesn't support `bmp`. I don't think anyone should be using `bmp` in web projects nowadays.

2020-05-25 18:29 UTC, yyx990803 commented on template-react-typescript/src/App.tsx
> +          Edit <code>App.jsx</code> and save to test HMR updates.
```suggestion
          Edit <code>App.tsx</code> and save to test HMR updates.
```

2020-05-26 03:04 UTC, xiaoxiangmoe commented
@yyx990803 done

2020-05-26 03:07 UTC, xiaoxiangmoe commented
@yyx990803 done

2020-05-26 03:12 UTC, xiaoxiangmoe commented
@yyx990803 done

2020-05-27 10:10 UTC, xiaoxiangmoe commented
@yyx990803 Can you review it? Thank you.

2020-05-27 13:41 UTC, yyx990803 commented
I made some adjustments to the base React template. Can you update it to match it (adjusted `index.html` location and build scripts)

Also need to bump `vite` and `vite-plugin-react` versions.

2020-05-27 16:08 UTC, daychongyang commented on template-react-typescript/src/react-app-env.d.ts
> +    readonly NODE_ENV: 'development' | 'production' | 'test'
The value of `process.env.NODE_ENV` is no longer fixed, it may be any string specified by the user using the `mode` option.

2020-05-27 16:08 UTC, daychongyang commented on template-react-typescript/.gitignore
> +dist
Can you add another line to ignore the local file(`*.local`)?

2020-05-28 03:37 UTC, xiaoxiangmoe commented
@yyx990803 @daychongyang
I completed the modification of `.gitignore`, `package.json` and `index.html`.

And I improved the jsdoc document of `process.env`.  If a user has passed in a new mode value, it should be marked in the npm script or elsewhere, and the corresponding literal type should be manually filled in `react-app-env.d.ts`.

2020-05-28 13:41 UTC, yyx990803 requested changes

2020-05-28 13:41 UTC, yyx990803 commented on template-react-typescript/package.json
> +    "vite": "^0.16.6",
```suggestion
    "vite": "^0.17.0",
```

2020-05-28 13:41 UTC, yyx990803 commented on template-react-typescript/package.json
> +    "vite-plugin-react": "^1.0.0"
```suggestion
    "vite-plugin-react": "^2.0.0"
```

2020-05-28 13:41 UTC, yyx990803 commented on template-react-typescript/index.html
> +  <script type="module" src="./src/main.tsx"></script>
```suggestion
  <script type="module" src="/src/main.tsx"></script>
```

This is necessary for SPA with history fallback

2020-05-28 13:42 UTC, merged